/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Landolt_C.gltf --transform
*/
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: { polySurface2: THREE.Mesh }
  materials: { lambert1: THREE.MeshStandardMaterial }
}

function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('Landolt_C.gltf') as GLTFResult

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface2.geometry} material={materials.lambert1} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

export default Model
useGLTF.preload('/Landolt_C.gltf')